services:
  - type: web
    name: voip-simulator-server
    env: node
    buildCommand: cd server && npm install
    startCommand: node server.js

  - type: web
    name: voip-simulator-client
    env: static
    staticPublishPath: client/dist
    buildCommand: cd client && npm install && npm run build
